name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: make
      run: make all
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: npm package
        path: 'npm/*.tgz'
