name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Cache emsdk
      id: cache-emsdk
      uses: actions/cache@v3
      with:
        path: vendor/emsdk/upstream
        key: ${{ runner.os }}-emsdk
    - name: Build dependencies
      id: cache-build-deps
      uses: actions/cache@v3
      with:
        path: out/em-Release/_deps
        key: ${{ runner.os }}-build-deps
    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: 8.5.0
        run_install: false
    - name: make
      run: make all
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: npm package
        path: 'npm/*.tgz'
